##########
# collectionbuilder-gh
# Jekyll Digital Collection Generator, designed for GitHub Pages
# https://github.com/CollectionBuilder/collectionbuilder-gh
##########

##########
# URL VARIABLES [optional if using GitHub Pages!]
#
# url is site domain, full URL to the production location of your collection
# on GitHub Pages follows the pattern username.github.io
#url: https://collectionbuilder.github.io 
# baseurl is path to location on the domain if necessary e.g. /digital/hjccc
# on GitHub Pages it is your github repository's name prefixed with a /
#baseurl: /collectionbuilder-gh 
# location of code, the full url to your github repository
source-code: https://github.com/CollectionBuilder/collectionbuilder-gh

##########
# SITE SETTINGS
#
# title of site appears in banner
title: The Murder of Ed Ballard in Telegrams 
# tagline, a short phrase that will appear throughout the site in the top banner
tagline: a collection of condolences sent to the Ballard family
# description appears in meta tags and other locations
# this description might appear in search result lists, keep around 160 characters max
description: "The Murder of Ed Ballard in Telegrams documents the aftermath of the murder of Ed Ballard, 1874-1936"
# creator of the digital collection, to appear in meta tags; we typically use our GitHub usernames but feel free to just use your name
author: Christian Tackett

##########
# COLLECTION SETTINGS
#
# Set the metadata for your collection (the name of the csv file in your _data directory that describes the objects in your collection) 
# Use the filename of your CSV **without** the ".csv" extension! E.g. _data/demo-metadata.csv --> "demo-metadata"
metadata: ballardmurdermetadata

##########
# Site/Organization Branding 
#   Uncomment these and enter information for your organization (replacing the CDIL links and name below) if you'd like to brand your site with a logo
#
# organization-name: "French Lick West Baden Museum"
# organization-link: flwbmuseum.com
# organization-logo-banner: https://static.wixstatic.com/media/0f12a1_5ed88cdc204c4b489ff1cf4d6d77a222~mv2.png/v1/fill/w_118,h_80,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/cce7c0_df210447fa2b4101bfb746b6f7078d8b.png
# organization-logo-nav: https://static.wixstatic.com/media/0f12a1_5ed88cdc204c4b489ff1cf4d6d77a222~mv2.png/v1/fill/w_118,h_80,al_c,q_85,usm_0.66_1.00_0.01,enc_avif,quality_auto/cce7c0_df210447fa2b4101bfb746b6f7078d8b.png

##########
# ROBOTS EXCLUDE
#
# set noindex to true if you do NOT want Google to index your site
# noindex: false 

##########
# BUILD SETTINGS 
#
# Note: use environment variable on build command to include analytics
# JEKYLL_ENV=production jekyll build
# (this is done automatically by gh-pages build)
#
# ignore stuff
exclude: [docs/, Rakefile, README.md, LICENSE, CITATION.cff, CODE_OF_CONDUCT.md, CONTRIBUTING.md]
# compress CSS output
sass:
  style: compressed
